source 'https://rubygems.org'

gem 'redsnow'
gem 'rake'
gem 'json-schema'
gem 'activesupport'
gem 'pry'
gem 'json-compare'

group :development, :test do
  gem 'guard-bundler'
  gem 'guard-ctags-bundler'
  gem 'guard-rspec'
  gem 'rspec'
end
