source 'https://rubygems.org'

gem 'redsnow'
gem 'rake'
gem 'json_schema'
gem 'activesupport'
gem 'pry'

group :development, :test do
  gem 'guard-bundler'
  gem 'guard-ctags-bundler'
  gem 'guard-rspec'
  gem 'rspec'
end
