#!/usr/bin/env ruby
require 'fileutils'

require 'bundler'
Bundler.require

$:.unshift File.join(File.dirname(__FILE__), "lib")
require "minimum_term"

desc "Clean up intermediary json files"
task :cleanup do
  files = Dir.glob(File.join(File.expand_path("../contracts"), "/**/*.json"))
  files.each do |file|
    FileUtils.rm(file)
  end
end

desc "Transform all MSON files to JSON Schema using drafter"
task :mson_to_json_schema, [:keep_intermediary_files] => :cleanup do |t, args|
  keep_intermediary_files = args[:keep_intermediary_files] == 'keep_intermediary_files'
  files = Dir.glob(File.join(File.expand_path("../contracts"), "/**/*.mson"))
  files.each do |file|
    if MinimumTerm::Conversion.mson_to_json_schema(file, keep_intermediary_files)
      puts "✅  #{file}"
    else
      puts "❌  #{file}"
    end
  end
end
