FORMAT: 1A
HOST: http://api.moviepilot.com/

# Edward

# Status [/v2]

We'll forward you to the v2 status resource

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "version": "5.2.0"
        }

## Group Posts

Resources related to posts in the API.

## Post [/v4/posts/{id}]

+ Parameters
    + id: `3461151` (integer, required) - External id

### View a post [GET]

+ Response 200 (application/json; charset=utf-8)

  + Body

            {
              "id": 3461151,
                "slug": "it-would-not-have-cost-marketing-any-more-money-to-add-black-widow-on",
                "title": "It would not have cost marketing any more money to add Black Widow on...",
                "html_body": "<p>... the cover (or Hawkeye, for that matter). And would it not have been better to take the chance at one more sale by having her on than to lose a sale by not having her on?And don't say that the main characters would then have been smaller because they could have placed Black Widow to the left and behind or above the main characters without changing their relative size.</p>",
                "total_comments_count": 0,
                "created_at": "2015-08-11T06:23:50.000-07:00",
                "questionnaire_id": null,
                "template": null,
                "abstract": null,
                "keywords": null,
                "cover_image_url": null,
                "cover_image_caption": null,
                "seo_title": null,
                "social_title": null,
                "social_abstract": null,
                "suggested_facebook_page_id": "1525889887653500",
                "comments_disabled": false,
                "is_mobile_post": false,
                "legacy_type": "post",
                "og_image_url": "http://images-cdn.moviepilot.com/image/upload/v1431953404/pocket_post_big2_ct9cex.png",
                "published_at": "2015-08-11T06:23:50.000-07:00",
                "first_published_at": "2015-08-11T06:23:50.000-07:00",
                "last_published_at": "2015-08-11T06:23:50.000-07:00",
                "promoted": null,
                "cover_video": {},
                "view_count": 0,
                "comment_count": 0,
                "author": {
                  "id": 1394326,
                  "name": "Richard Lemay",
                  "first_name": "Richard",
                  "last_name": "Lemay",
                  "user_name": null,
                  "image_url": "https://graph.facebook.com/695180451/picture",
                  "description": null,
                  "followers_count": 1,
                  "verified": "contributor",
                  "user_subscription_count": 3,
                  "weekly_readers": 0,
                  "contributions_count": 1,
                  "contribution_view_count": 0,
                  "contribution_comments_count": 0,
                  "facebook_id": "695180451",
                  "twitter_handle": null,
                  "location": null,
                  "avatar_image_url": null,
                  "cover_image_url": null,
                  "provider_image_url": "https://graph.facebook.com/695180451/picture",
                  "flags": [],
                  "roles": [
                    "contributor"
                    ],
                  "profile_public": true,
                  "auto_promote_posts": true
                },
                "in_reply_to": {
                  "id": 3457913,
                  "type": "post",
                  "first_published_at": "2015-08-10T07:02:09.000-07:00",
                  "last_published_at": "2015-08-10T07:17:08.000-07:00",
                  "slug": "black-widow-was-just-snubbed-by-marvel-again",
                  "title": "Black Widow Was Just Snubbed by Marvel...AGAIN",
                  "author": {
                    "id": 1311215,
                    "name": "Kit Simpson Browne",
                    "user_name": "Kitsb"
                  }
                },
                "related_objects": [
                {
                  "id": 205406,
                  "type": "tag",
                  "slug": "superheroes",
                  "name": "Superheroes",
                  "image_url": "http://images-cdn.moviepilot.com/image/upload/c_fill,h_237,t_mp_quality,w_600/-14cf0c53-33e1-41be-abb6-4490542ec6db.gif",
                  "subscriber_count": 45802
                },
                {
                  "id": 932254,
                  "type": "tag",
                  "slug": "marvel",
                  "name": "Marvel",
                  "image_url": "http://images-cdn.moviepilot.com/image/upload/c_fill,h_211,t_mp_quality,w_500/-76cc31d4-897f-486c-9dbb-8e22fd30cf1b.gif",
                  "subscriber_count": 8627
                },
                {
                  "id": 958506,
                  "type": "tag",
                  "slug": "casting",
                  "name": "Casting",
                  "image_url": "http://images-cdn.moviepilot.com/image/upload/c_fill,h_400,t_mp_quality,w_960/-364bed3a-81c7-4e44-8735-3500b536e23d.jpg",
                  "subscriber_count": 668
                },
                {
                  "id": 958518,
                  "type": "tag",
                  "slug": "opinion",
                  "name": "Opinion",
                  "image_url": "http://images-cdn.moviepilot.com/image/upload/c_fill,h_205,t_mp_quality,w_400/-f08c141c-387b-4dc2-a399-8aadd4084155.gif",
                  "subscriber_count": 236
                },
                {
                  "id": 958527,
                  "type": "tag",
                  "slug": "industry",
                  "name": "Industry",
                  "image_url": "http://images-cdn.moviepilot.com/image/upload/c_fill,h_235,t_mp_quality,w_416/-71298c11-8adb-4db0-8375-7d921f732dc2.gif",
                  "subscriber_count": 9
                },
                {
                  "id": 958545,
                  "type": "tag",
                  "slug": "rumors",
                  "name": "Rumors",
                  "image_url": "http://images-cdn.moviepilot.com/image/upload/c_fill,h_433,t_mp_quality,w_580/-b44f55e3-0f23-4192-bf77-de110b2f7f9a.gif",
                  "subscriber_count": 178
                },
                {
                  "id": 959395,
                  "type": "tag",
                  "slug": "creators",
                  "name": "Creators",
                  "image_url": "http://images-cdn.moviepilot.com/image/upload/c_fill,h_600,t_mp_quality,w_600/-10293491-38f3-4d79-a119-1897cd86c90a.jpg",
                  "subscriber_count": 657
                },
                {
                  "id": 959428,
                  "type": "tag",
                  "slug": "news",
                  "name": "News",
                  "image_url": "http://images-cdn.moviepilot.com/image/upload/c_fill,h_450,t_mp_quality,w_960/-e837b84b-712a-4c9a-8663-3117601c7856.jpg",
                  "subscriber_count": 665
                },
                {
                  "id": 960923,
                  "type": "tag",
                  "slug": "editorial",
                  "name": "Editorial",
                  "image_url": "http://images-cdn.moviepilot.com/image/upload/c_fill,h_300,t_mp_quality,w_500/-daff61f2-3d14-4c50-ac51-1ece761e6c71.gif",
                  "subscriber_count": 60
                },
                {
                  "id": 978148,
                  "type": "tag",
                  "slug": "dvd-blu-ray",
                  "name": "DVD & Blu-ray",
                  "image_url": "http://images-cdn.moviepilot.com/image/upload/c_fill,h_235,t_mp_quality,w_500/-c6dfb789-4d04-4810-a627-5cce20d77e19.gif",
                  "subscriber_count": 27
                },
                {
                  "id": 1070824,
                  "type": "tag",
                  "slug": "black-widow",
                  "name": "Black Widow",
                  "image_url": "http://images-cdn.moviepilot.com/image/upload/c_fill,h_380,t_mp_quality,w_920/-ee6baf50-8e27-491a-b2a5-4fbea6edfa2a.jpg",
                  "subscriber_count": 1573
                },
                {
                  "id": 1096390,
                  "type": "tag",
                  "slug": "mcu",
                  "name": "Marvel Cinematic Universe",
                  "image_url": "http://images-cdn.moviepilot.com/image/upload/c_fill,h_250,t_mp_quality,w_500/-f71691fc-3123-40ce-8b56-bc14a69f1527.gif",
                  "subscriber_count": 2076
                },
                {
                  "id": 1327911,
                  "type": "tag",
                  "slug": "plot",
                  "name": "Plot",
                  "image_url": "http://images-cdn.moviepilot.com/image/upload/c_fill,h_463,t_mp_quality,w_850/-ee8b3c7a-6017-4208-8753-0eeee8ba2c6c.png",
                  "subscriber_count": 3
                }
              ]
            }


    + Attributes
        - id: 1 (number, required) - The unique identifier for a product
        - name: A green door (string, required) - Name of the product
        - price: 12.50 (number, required)
        - tags: home, green (array[string])
