FORMAT: 1A
HOST: http://api.moviepilot.com/

# Edward

# Status [/v2]

## GET

+ Response 200 (application/json)
  + Body
    + Attributes
      - name: Mila (string, required) - Given name
      - email: hello@max-and-mila.com (string, optional) - User's email
